global:
  appName: 'synergy-nuxt3'
  dev:
    instanceCount: '1'

    log:
      host: 'syslog2.synergy.ru'
      port: '12201'
    apiUrl: "https://api.sglobaltrade.com/api/"
    fbPixel: "XXX"
    gtm: "XXX"
    s3UrlBacket: "XXX"

  prod:
    instanceCount: '1'
    log:
      host: 'syslog.synergy.ru'
      port: '12201'
    apiUrl: "https://api.sglobaltrade.com/api/"
    fbPixel: "XXX"
    gtm: "XXX"
    s3UrlBacket: "XXX"

redirects: []

mirrors: []
